[build]
  command = "npm run build && cp ad3c95ac-08c0-4d3b-9dde-1fa4bc5b2516.png out/logo.png && cp 1.jpg 2.jpg 3.jpg 4.jpg 5.jpg 6.jpg out/"
  publish = "out"

[build.environment]
  NODE_VERSION = "22"
  NEXT_TELEMETRY_DISABLED = "1"
